#!/usr/bin/env python3
import i3ipc
 
i3 = i3ipc.Connection()

splitv_text = '↓'
splith_text = '→'
split_none_text  = '•'
 
 
def on_event(self, _):
    parent = i3.get_tree().find_focused().parent
    if parent.layout == 'splitv':
        print(splitv_text, flush=True)
    elif parent.layout == 'splith':
        print(splith_text, flush=True)
    else:
    	print(split_none_text, flush=True)
 
 
# Subscribe to events
i3.on("window::focus", on_event)
i3.on("binding", on_event)
 
# Start the main loop and wait for events to come in.
i3.main()
